import type { Metadata } from "next";
import { Marhey } from "next/font/google";
import "@/styles/globals.css";

const marhey = Marhey({ subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "بنت ولد نبات جماد حيوان بلاد",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>بنت ولد نبات جماد حيوان بلاد</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="بنت ولد نبات جماد حيوان بلاد" />
        <link rel="icon" href="/favicon.ico" sizes="any" as="image" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        {/* eslint-disable-next-line @next/next/no-page-custom-font */}
        <link
          href="https://fonts.googleapis.com/css2?family=Aref+Ruqaa:wght@400;700&family=Marhey:wght@300..700&family=Noto+Kufi+Arabic:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>

      <body
        className={`${marhey.className} bg-gray-900 flex flex-col min-h-screen rtl`}
      >
        {children}
      </body>
    </html>
  );
}
